WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 600

TUBE_WIDTH = 100
TUBE_HEIGHT = 250
TUBE_THICKNESS = 5
COLOR_HEIGHT = int(2*(TUBE_HEIGHT-TUBE_THICKNESS*2)/9)
TUBE_MARGIN = TUBE_HEIGHT-TUBE_THICKNESS*2-4*COLOR_HEIGHT
TUBE_ANIME_TIME = 25
NO_ANIME = 0

BUTTON_WIDTH = 80
BUTTON_HEIGHT = 80